kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-$TARGET
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv-$TARGET
