from debian
run apt-get update
run apt-get install -y restic curl gnupg2 lsb-release mariadb-client postgresql-common
run sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
run apt-get update
run apt-get -y install postgresql-client-16
copy backup.py /