apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ngnix-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - geoserver1.prahounakole.cz
    - mapa.prahounakole.cz
    - klub.prahounakole.cz
    - klub.auto-mat.cz
    - mapa-test.prahounakole.cz
    - "*.dopracenakole.net"
    secretName: ngnix-kubernetes-tls
  rules:
  - host: geoserver1.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: geoserver
          servicePort: 8080
  - host: mapa-test.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: mapa-test
          servicePort: 8000
  - host: mapa.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: klub.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: klub-automat
          servicePort: 8000
  - host: klub.auto-mat.cz
    http:
      paths:
      - backend:
          serviceName: klub-automat
          servicePort: 8000
  - host: breclav.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: brno.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: budejovice.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: hradec.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: jablonec.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: jihlava.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: jindrichuv-hradec.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: karvina.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: liberec.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: olomouc.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: opava.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: ostrava.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: otrokovice.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: pardubice.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: plzen.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: prerov.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: hradiste.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: usti.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: zlin.dopracenakole.net
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
