apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ngnix-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - geoserver1.prahounakole.cz
    - mapa.prahounakole.cz
    secretName: ngnix-kubernetes-tls
  rules:
  - host: geoserver1.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: geoserver
          servicePort: 8080
  - host: mapa.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
