apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ngnix-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
spec:
  tls:
  - hosts:
    - geoserver1.prahounakole.cz
    - mapa.prahounakole.cz
    - klub.prahounakole.cz
    - klub.auto-mat.cz
    - mapa-test.prahounakole.cz
    - breclav.dopracenakole.net
    - brno.dopracenakole.net
    - budejovice.dopracenakole.net
    - hradec.dopracenakole.net
    - jablonec.dopracenakole.net
    - jablonec.dopracenakole.net
    - jindrichuv-hradec.dopracenakole.net
    - karvina.dopracenakole.net
    - liberec.dopracenakole.net
    - olomouc.dopracenakole.net
    - opava.dopracenakole.net
    - ostrava.dopracenakole.net
    - otrokovice.dopracenakole.net
    - pardubice.dopracenakole.net
    - plzen.dopracenakole.net
    - prerov.dopracenakole.net
    - hradiste.dopracenakole.net
    - usti.dopracenakole.net
    - zlin.dopracenakole.net
    secretName: ngnix-kubernetes-tls
  rules:
  - host: geoserver1.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: geoserver
          servicePort: 8080
  - host: mapa-test.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: mapa-test
          servicePort: 8000
  - host: mapa.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
  - host: klub.prahounakole.cz
    http:
      paths:
      - backend:
          serviceName: klub-automat
          servicePort: 8000
  - host: klub.auto-mat.cz
    http:
      paths:
      - backend:
          serviceName: klub-automat
          servicePort: 8000
  - host: "*.dopracenakole.net"
    http:
      paths:
      - backend:
          serviceName: mapa
          servicePort: 8000
