apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flower-minikube
  labels:
    deployment: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-flower
  template:
    metadata:
      labels:
        pod: celery-flower
    spec:
      containers:
      - name: flower-minikube
        image: petrdlouhy/dopracenakole:latest
        command: ['celery', 'flower', '-A', 'project.celery' , 'flower']
        ports:
          - containerPort: 5555
          envFrom:
            - configMapRef:
                name: dpnk-minikube-config
            - secretRef:
                name: dpnk-minikube-credentials

        env:
            - name: REDIS_HOST
              value: redis-service-minikube
        resources:
          limits:
            cpu: 100m
