#@ app_name = "dpnk-automat-staff"
#@ image = "auto0mat/dopracenakole:2025.2103"
#@ config_map = "dpnk-automat-staff-env"
#@ secret_map = "dpnk-access"
#@ load("dpnk.lib.yml", "web")
--- #@ web(app_name, image, config_map, secret_map, 1, 1)
