version: 2.1
workflows:
  version: 2
  deploy:
    jobs:
      - apply:
          filters:
            branches:
              only:
                - master

jobs:
  apply:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
            curl -LO https://github.com/vmware-tanzu/carvel-ytt/releases/download/v0.31.0/ytt-linux-amd64
            mv ytt-linux-amd64 ytt
            chmod +x ./ytt
      - run:
          name: Deploy Code
          command: PATH=$PATH:$PWD ./apply.sh
      - setup_remote_docker:
          reusable: true
      - run:
          name: Build backup docker image
          command: ./backups/build.py
