apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: passbolt
  spec:
    ports:
    - name: "web"
      port: 80
      targetPort: 80
    selector:
      app: passbolt
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: passbolt
    name: passbolt
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: passbolt
    template:
      metadata:
        labels:
          app: passbolt
      spec:
        containers:
        - image: passbolt/passbolt
          name: passbolt
          ports:
          - containerPort: 80
          resources: {}
          volumeMounts:
          - mountPath: /etc/passbolt/gpg/
            name: passbolt-keys
          - name: passbolt-avatars
            mountPath: /var/lib/passbolt/tmp/avatars/
          env:
          - name: DATASOURCES_DEFAULT_HOST
            valueFrom:
              configMapKeyRef:
                key: DATASOURCES_DEFAULT_HOST
                name: passbolt-env
          - name: DATASOURCES_DEFAULT_DATABASE
            valueFrom:
              configMapKeyRef:
                key: DATASOURCES_DEFAULT_DATABASE
                name: passbolt-env
          - name: APP_FULL_BASE_URL
            valueFrom:
              configMapKeyRef:
                key: APP_FULL_BASE_URL
                name: passbolt-env
          - name: DATASOURCES_DEFAULT_USERNAME
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: DATASOURCES_DEFAULT_USERNAME
          - name: DATASOURCES_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: DATASOURCES_DEFAULT_PASSWORD
          - name: EMAIL_DEFAULT_FROM
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: EMAIL_DEFAULT_FROM
          - name: EMAIL_TRANSPORT_DEFAULT_HOST
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: EMAIL_TRANSPORT_DEFAULT_HOST
          - name: EMAIL_TRANSPORT_DEFAULT_USERNAME
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: EMAIL_TRANSPORT_DEFAULT_USERNAME
          - name: EMAIL_TRANSPORT_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: EMAIL_TRANSPORT_DEFAULT_PASSWORD
          - name: EMAIL_TRANSPORT_DEFAULT_TLS
            valueFrom:
              secretKeyRef:
                name: passbolt-access
                key: EMAIL_TRANSPORT_DEFAULT_TLS
        volumes:
          - name: passbolt-keys
            secret:
              secretName: passbolt-access
              items:
              - key: passbolt-serverkey
                path: serverkey.asc
              - key: passbolt-serverkey-private
                path: serverkey_private.asc
          - name: passbolt-avatars
            persistentVolumeClaim:
              claimName: passbolt-avatars-claim

  status: {}
kind: List
metadata: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passbolt-avatars-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
