apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-mnk-rendering-renderd-service
spec:
  schedule: "0 */4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restart-mnk-rendering-renderd-service
            image: auto0mat/restart-mnk-rendering-renderd-service:0
            args:
            - restart_renderd_service.sh
            env:
            - name: DO_KUBERNETES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: check-nfs-kernel-server-service-access
                  key: DO_KUBERNETES_TOKEN
            - name: DO_KUBERNETES_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: check-nfs-kernel-server-service-access
                  key: DO_KUBERNETES_CLUSTER_ID
            - name: DO_KUBERNETES_CLUSTER_CREDENTIALS_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: check-nfs-kernel-server-service-access
                  key: DO_KUBERNETES_CLUSTER_CREDENTIALS_EXPIRY
          restartPolicy: Never
