apiVersion: batch/v1
kind: Job
metadata:
  name: django-initial-migrations-minikube
spec:
  template:
    spec:
      containers:
        - name: django
          image: petrdlouhy/dopracenakole:latest
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: dpnk-minikube-config
            - secretRef:
                name: dpnk-general-credentials
            - secretRef:
                name: dpnk-minikube-credentials
      restartPolicy: Never
  backoffLimit: 5
