#!/bin/bash
kubectl get pods | grep ContainerStatusUnknown | awk '{print $1}' | xargs kubectl delete pod
kubectl get pods | grep Error | awk '{print $1}' | xargs kubectl delete pod
kubectl get pods | grep Evicted | awk '{print $1}' | xargs kubectl delete pod
