kind: ConfigMap
apiVersion: v1
metadata:
  name: bugzilla-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:BUGS_CONTEXT': {}
data:
  BUGS_CONTEXT: "http://localhost:8080"
