kind: ConfigMap
apiVersion: v1
metadata:
  name: city-experience-differently-frontend-test-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:API_BASE": {}
data:
  API_BASE: test
