kind: ConfigMap
apiVersion: v1
metadata:
  name: dpnk-env
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: 'project.settings.rtwbb_prod'
  DJANGO_DEBUG: "False"
  DPNK_LOG_FILE: "dpnk.log"
  DPNK_ALLOWED_HOSTS: ".dopracenakole.net,localhost,$HEALTHY_CHECK_IP,dpnk-132639103.eu-west-1.elb.amazonaws.com"
  DPNK_MEDIA_URL: "https://s3-eu-west-1.amazonaws.com/dpnk/"
  DPNK_STATIC_URL: "https://dlxsohmbtwaie.cloudfront.net/static/"
  DPNK_BROKER_URL: "redis://dpnk-redis-broker"
  DPNK_CACHE_REDIS_LOCATION: "redis://dpnk-redis-cache"
  SINGLE_BEAT_REDIS_SERVER: "redis://dpnk-redis-beat"
  DPNK_PRODUCTION_ENVIRONMENT: "True"
  CELERY_TASK_QUEUES: "stravasync,celery"
  GLS_BASE_URL: "https://online.gls-czech.com"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_FROM: "31.01.2025"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_TO: "date +%d.%m.%Y"
  HELPDESK_IFRAME_URL: "None"
  DPNK_AKLUB_URL: "https://automat.klub-pratel.cz"
  GUNICORN_NUM_WORKERS: "4"
  GUNICORN_NUM_THREADS: "4"
  GUNICORN_TIMEOUT: "4000"
  GUNICORN_PORT: "8000"
  AWS_QUERYSTRING_AUTH: "True"
  FAKTUROID_INVOICE_NUMBER_WIDTH: "4"
  FAKTUROID_BASE_REST_API_URL: "https://app.fakturoid.cz/api/v3"
  FAKTUROID_DATE_FROM_CREATE_INVOICES: "2022-04-29"
  DISABLE_SERVER_SIDE_CURSORS: "True"
  CELERY_CONCURENCY: "8"
  DPNK_SITE_ID: "36"
  USE_BJOERN_WSGI_SERVER: "True"
  STATSD_SERVER_HOST: "statsd"
  STATSD_SERVER_PORT: "8125"
  STATSD_SERVER_NAME_SPACE: "bjoern-dpnk"
  BJOERN_WSGI_SERVER_NUM_WORKERS: "8"
  DPNK_DATA_UPLOAD_MAX_MEMORY_SIZE: "10485760"
  DPNK_FILE_UPLOAD_MAX_MEMORY_SIZE: "10485760"
  PAYU_TEST_REST_API_AUTH_URL: "https://secure.snd.payu.com/pl/standard/user/oauth/authorize"
  PAYU_TEST_REST_API_CREATE_ORDER_URL: "https://secure.snd.payu.com/api/v2_1/orders"
  PAYU_TEST_REST_API_CREATE_ORDER_CURRENCY_CODE: "PLN"
  PAYU_PRODUCTION_REST_API_AUTH_URL: "https://secure.payu.com/pl/standard/user/oauth/authorize"
  PAYU_PRODUCTION_REST_API_CREATE_ORDER_URL: "https://secure.payu.com/api/v2_1/orders"
  PAYU_PRODUCTION_REST_API_CREATE_ORDER_CURRENCY_CODE: "CZK"
  USE_PAYU_TEST_CONF: "False"
  RTWBB_FRONTEND_APP_BASE_URL: "https://dpnk.dopracenakole.cz/#/"
  SOCIALACCOUNT_EMAIL_AUTHENTICATION: "True"
