kind: ConfigMap
apiVersion: v1
metadata:
  name: dpnk-test-env
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: 'project.settings.base'
  DPNK_ALLOWED_HOSTS: .dopracenakole.cz,localhost,$HEALTHY_CHECK_IP,dpnk-test-1366503246.eu-west-1.elb.amazonaws.com
  DJANGO_DEBUG: "False"
  DPNK_STATIC_URL: "https://d3fsxj6ulepi0p.cloudfront.net/static/"
  DPNK_AKLUB_URL: "https://devel-klub.auto-mat.cz"
  GUNICORN_NUM_WORKERS: "2"
  GUNICORN_NUM_THREADS: "2"
  GUNICORN_TIMEOUT: "4000"
  GUNICORN_PORT: "8000"
  GLS_BASE_URL: "http://test.online.gls-czech.com"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_FROM: "01.01.2019"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_TO: "31.12.2019"
  AWS_QUERYSTRING_AUTH: "True"
  DPNK_LOG_FILE: "dpnk.log"
  DPNK_MEDIA_URL: "https://s3-eu-west-1.amazonaws.com/dpnk-test/"
  DPNK_BROKER_URL: "redis://dpnk-test-redis-broker"
  DPNK_CACHE_REDIS_LOCATION: "redis://dpnk-test-redis-cache"
  SINGLE_BEAT_REDIS_SERVER: "redis://dpnk-test-redis-beat"
  METABASE_APP_DOMAIN: "https://metabase.dopracenakole.net/"
  METABASE_DPNK_INDIVIDUAL_DATA_REPORT_URL: "public/dashboard/3aa559ac-dd2b-4dd5-96d2-792b20fb39cf"
  METABASE_DPNK_ORGANIZATION_DATA_REPORT_URL: "public/dashboard/fa0f4d70-62df-48cc-920c-2813f6e25078"
  METABASE_DPNK_CITY_DATA_REPORT_URL: "public/dashboard/f91c362f-0eff-492c-92c7-97fea1505909"
  FAKTUROID_INVOICE_NUMBER_WIDTH: "4"
  FAKTUROID_BASE_REST_API_URL: "https://app.fakturoid.cz/api/v2"
  FAKTUROID_DATE_FROM_CREATE_INVOICES: ""
  DISABLE_SERVER_SIDE_CURSORS: "True"
  CELERY_CONCURENCY: "8"
  DPNK_SITE_ID: "1"
  USE_BJOERN_WSGI_SERVER: "False"
  STATSD_SERVER_HOST: "statsd"
  STATSD_SERVER_PORT: "8125"
  STATSD_SERVER_NAME_SPACE: "bjoern-dpnk-test"
  BJOERN_WSGI_SERVER_NUM_WORKERS: "1"
