kind: ConfigMap
apiVersion: v1
metadata:
  name: klub-diakonie-env
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: 'project.settings.k8s'
  AKLUB_DEBUG: "False"
  AWS_STORAGE_BUCKET_NAME: diakonie-klub-prod-real
  AKLUB_CORS_ORIGIN_WHITELIST: "https://www.diakonie.cz"
  AKLUB_DEFAULT_FROM_EMAIL: kp@auto-mat.cz
  AKLUB_MEDIA_ROOT: ""
  GUNICORN_WORKERS: "2"
  GUNICORN_TIMEOUT: "30"
  HEROKU_APP_URL: "crm.diakonie.cz"
  AKLUB_ALLOWED_HOSTS: "diakonie.klub-pratel.cz"
  SITE_NAME: Automat Klub přatel
  SUM_LAST_MONTH_PAYMENTS: 0
  SUM_LAST_YEAR_PAYMENTS: 0
  AWS_QUERYSTRING_EXPIRE: 300
  WEB_URL: ""
