kind: ConfigMap
apiVersion: v1
metadata:
  name: klub-diakonie-env
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: 'project.settings.k8s'
  AKLUB_DEBUG: "False"
  AWS_STORAGE_BUCKET_NAME: automat-diakonie-prod-real
  AKLUB_CORS_ORIGIN_WHITELIST: ""
  AKLUB_DEFAULT_FROM_EMAIL: kp@auto-mat.cz
  AKLUB_MEDIA_ROOT: ""
  GUNICORN_WORKERS: "2"
  GUNICORN_TIMEOUT: "30"
  HEROKU_APP_URL: "crm.diakonie.cz"
