kind: ConfigMap
apiVersion: v1
metadata:
  name: limesurvey-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:DB_TYPE": {}
data:
  DB_TYPE: "pgsql"
