kind: ConfigMap
apiVersion: v1
metadata:
  name: limesurvey-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:DB_TYPE": {}
          "f:POSTGRES_ENV_GOSU_VERSION": {}
data:
  DB_TYPE: "pgsql"
  POSTGRES_ENV_GOSU_VERSION: "pgsql"
  SMTP_AUTH: "on"
  SMTP_TLS: "on"
  MAIL_FROM_DEFAULT: "kontakt@dopracenakole.cz"
  MAIL_DOMAIN: "dopracenakole.cz"
  SMTP_TLS_CHECK: "on"
  SMTP_STARTTLS: "on"
  SMTP_TLS_TRUST_FILE: "/etc/ssl/certs/ca-certificates.crt"