kind: ConfigMap
apiVersion: v1
metadata:
  name: mapa-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:DB_NAME': {}
          'f:DJANGO_SETTINGS_MODULE': {}
          'f:AKLUB_ALLOWED_HOSTS': {}
          'f:DEBUG': {}
          'f:AWS_STORAGE_BUCKET_NAME': {}
          'f:S3_MEDIA_ROOT': {}
          'f:GUNICORN_TIMEOUT': {}
data:
  DB_NAME: 'mapa'
  DJANGO_SETTINGS_MODULE: 'project.settings.base'
  AKLUB_ALLOWED_HOSTS: '.prahounakole.cz:.dopracenakole.net'
  DEBUG: 'False'
  AWS_STORAGE_BUCKET_NAME: 'cyklomapa-media'
  S3_MEDIA_ROOT: 'https://cyklomapa-media.s3-eu-west-1.amazonaws.com/'
  GUNICORN_TIMEOUT: '300'
