kind: ConfigMap
apiVersion: v1
metadata:
  name: mapa-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:DB_NAME': {}
          'f:DJANGO_SETTINGS_MODULE': {}
          'f:AKLUB_ALLOWED_HOSTS': {}
          'f:DEBUG': {}
data:
  DB_NAME: 'pnk'
  DJANGO_SETTINGS_MODULE: 'project.settings.base'
  AKLUB_ALLOWED_HOSTS: '.prahounakole.cz'
  DEBUG: 'True'
