kind: ConfigMap
apiVersion: v1
metadata:
  name: mapa-test-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:DB_NAME': {}
          'f:DJANGO_SETTINGS_MODULE': {}
          'f:AKLUB_ALLOWED_HOSTS': {}
          'f:DEBUG': {}
          'f:AWS_STORAGE_BUCKET_NAME': {}
          'f:S3_MEDIA_ROOT': {}
          'f:GUNICORN_TIMEOUT': {}
          'f:DISABLE_SERVER_SIDE_CURSORS': {}
          'f:CONN_MAX_AGE': {}
          'f:GEOAPIFY_AUTOCOMPLETE_API_URL': {}
data:
  DB_NAME: 'mapa-pool'
  DJANGO_SETTINGS_MODULE: 'project.settings.base'
  AKLUB_ALLOWED_HOSTS: '.prahounakole.cz:.dopracenakole.net'
  DEBUG: 'True'
  AWS_STORAGE_BUCKET_NAME: 'cyklomapa-media'
  S3_MEDIA_ROOT: 'https://cyklomapa-media.s3-eu-west-1.amazonaws.com/'
  GUNICORN_TIMEOUT: '300'
  DISABLE_SERVER_SIDE_CURSORS: 'True'
  CONN_MAX_AGE: '60'
  GEOAPIFY_AUTOCOMPLETE_API_URL: 'https://api.geoapify.com/v1/geocode/autocomplete'
