kind: ConfigMap
apiVersion: v1
metadata:
  name: passbolt-env
  namespace: default
data:
  DATASOURCES_DEFAULT_HOST: 'mysql'
  DATASOURCES_DEFAULT_DATABASE: 'passbolt'
  APP_FULL_BASE_URL: 'https://automat.passbolt.klub-pratel.cz'
