kind: ConfigMap
apiVersion: v1
metadata:
  name: db-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:ALLOW_IP_RANGE': {}
          'f:POSTGRES_DB': {}
          'f:POSTGRES_USER': {}
data:
  ALLOW_IP_RANGE: 0.0.0.0/0
  POSTGRES_DB: 'pnk'
  POSTGRES_USER: docker
