kind: ConfigMap
apiVersion: v1
metadata:
  name: ride-to-work-by-bike-backend-test-env
  namespace: default
data:
  DJANGO_SETTINGS_MODULE: 'project.settings.rtwbb_test'
  DPNK_ALLOWED_HOSTS: .dopracenakole.net,localhost,$HEALTHY_CHECK_IP,dpnk-test-1366503246.eu-west-1.elb.amazonaws.com
  DJANGO_DEBUG: "False"
  DPNK_STATIC_URL: "https://d3fsxj6ulepi0p.cloudfront.net/static/"
  DPNK_AKLUB_URL: "https://devel-klub.auto-mat.cz"
  GUNICORN_NUM_WORKERS: "2"
  GUNICORN_NUM_THREADS: "2"
  GUNICORN_TIMEOUT: "4000"
  GUNICORN_PORT: "8000"
  GLS_BASE_URL: "http://test.online.gls-czech.com"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_FROM: "01.01.2019"
  GLS_DISPATCHED_SUBSIDIARY_BOXES_DATE_TO: "31.12.2019"
  AWS_QUERYSTRING_AUTH: "True"
  DPNK_LOG_FILE: "dpnk.log"
  DPNK_MEDIA_URL: "https://s3-eu-west-1.amazonaws.com/dpnk-test/"
  DPNK_BROKER_URL: "redis://ride-to-work-by-bike-backend-test-redis-broker"
  DPNK_CACHE_REDIS_LOCATION: "redis://ride-to-work-by-bike-backend-test-redis-cache"
  SINGLE_BEAT_REDIS_SERVER: "redis://ride-to-work-by-bike-backend-test-redis-beat"
  FAKTUROID_INVOICE_NUMBER_WIDTH: "4"
  FAKTUROID_BASE_REST_API_URL: "https://app.fakturoid.cz/api/v3"
  FAKTUROID_DATE_FROM_CREATE_INVOICES: ""
  DISABLE_SERVER_SIDE_CURSORS: "True"
  CELERY_CONCURENCY: "8"
  DPNK_SITE_ID: "1"
  USE_BJOERN_WSGI_SERVER: "False"
  STATSD_SERVER_HOST: "statsd"
  STATSD_SERVER_PORT: "8125"
  STATSD_SERVER_NAME_SPACE: "bjoern-ride-to-work-by-bike-backend-test"
  BJOERN_WSGI_SERVER_NUM_WORKERS: "1"
  DPNK_DATA_UPLOAD_MAX_MEMORY_SIZE: "5242880"
  DPNK_FILE_UPLOAD_MAX_MEMORY_SIZE: "5242880"
  PAYU_TEST_REST_API_AUTH_URL: "https://secure.snd.payu.com/pl/standard/user/oauth/authorize"
  PAYU_TEST_REST_API_CREATE_ORDER_URL: "https://secure.snd.payu.com/api/v2_1/orders"
  PAYU_TEST_REST_API_CREATE_ORDER_CURRENCY_CODE: "PLN"
  PAYU_PRODUCTION_REST_API_AUTH_URL: "https://secure.snd.payu.com/pl/standard/user/oauth/authorize"
  PAYU_PRODUCTION_REST_API_CREATE_ORDER_URL: "https://secure.snd.payu.com/api/v2_1/orders"
  PAYU_PRODUCTION_REST_API_CREATE_ORDER_CURRENCY_CODE: "PLN"
  USE_PAYU_TEST_CONF: "True"
  RTWBB_FRONTEND_APP_BASE_URL: "https://localhost:9000/#/"
  SOCIALACCOUNT_EMAIL_AUTHENTICATION: "True"
  DPNK_MOBILE_APP_SIMPLE_JWT_TOKEN_LIFETIME: "36500"
  DPNK_MOBILE_APP_SIMPLE_JWT_TOKEN_LIFETIME_UNIT: "days"