apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: dpnk-test
  name: dpnk-test
  selfLink: /apis/apps/v1/namespaces/default/deployments/dpnk-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dpnk-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: dpnk-test
      name: dpnk-test
    spec:
      containers:
      - image: petrdlouhy/dopracenakole-testing:latest
        imagePullPolicy: IfNotPresent
        name: dpnk-test
        command: [ "/home/aplikace/docker-celery-entrypoint.sh" ]
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: DPNK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: secret-key
          - name: DPNK_LOG_FILE
            value: dpnk.log
          - name: DPNK_DB_NAME
            value: dpnk_2017
          - name: DPNK_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: db-password
          - name: DPNK_DB_HOST
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: db-host
          - name: DPNK_DB_USER
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: db-user
          - name: DPNK_ALLOWED_HOSTS
            value: .dopracenakole.cz,$HEALTHY_CHECK_IP,dpnk-test-1366503246.eu-west-1.elb.amazonaws.com
          - name: DPNK_MAILING_API_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: mailing-api-key
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: new-relic-license-key
          - name: NEW_RELIC_APP_NAME
            value: Do prace na kole - test
          - name: DPNK_MEDIA_URL
            value: https://s3-eu-west-1.amazonaws.com/dpnk-test/
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: new-relic-license-key
          - name: DPNK_AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: aws-access-key
          - name: DPNK_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-test-credentials
                key: aws-secret-access-key
          - name: DPNK_AWS_STORAGE_BUCKET_NAME
            value: dpnk-test
          - name: DPNK_PAYU_KEY_1
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: payu-key-1
          - name: DPNK_PAYU_KEY_2
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: payu-key-2
          - name: DPNK_PAYU_POS_AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: payu-pos-auth-key
          - name: DPNK_PAYU_POS_ID
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: payu-pos-id
          - name: DPNK_FIO_TOKEN
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: fio-token
          - name: DPNK_RAVEN_DNS
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: raven-dns
          - name: DPNK_GOOGLE_TAG_ID
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: google-tag-id
          - name: DPNK_SOCIAL_AUTH_FACEBOOK_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: social-auth-facebook-key
          - name: DPNK_SOCIAL_AUTH_FACEBOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: social-auth-facebook-secret
          - name: DPNK_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: social-auth-google-oauth2-key
          - name: DPNK_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: social-auth-google-oauth2-secret
          - name: DPNK_STATIC_URL
            value: https://d3fsxj6ulepi0p.cloudfront.net/static/
          - name: DPNK_AKLUB_URL
            value: https://devel-klub.auto-mat.cz
          - name: DPNK_HEADER_COLOR
            value: blue
          - name: STRAVA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: strava-client-id
          - name: STRAVA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dpnk-general-credentials
                key: strava-client-secret
          - name: GUNICORN_NUM_WORKERS
            value: "2"
          - name: DPNK_BROKER_URL
            value: redis://dpnk.nnlokn.ng.0001.euw1.cache.amazonaws.com:6379/5
          - name: DPNK_CACHE_REDIS_LOCATION
            value: redis://dpnk.nnlokn.ng.0001.euw1.cache.amazonaws.com:6379/6
          - name: SINGLE_BEAT_REDIS_SERVER
            value: redis://dpnk.nnlokn.ng.0001.euw1.cache.amazonaws.com:6379/7
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
